name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Build TipTap plugin
        run: |
          release_version=$(cat plugins/tiptap/package.json | jq -r '.version')
          echo "RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          pnpm build

      - name: Perform Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: tiptap-v${{ env.RELEASE_VERSION }}
          tag_name: tiptap-v${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          files: |
            plugins/tiptap/dist/*.tar.gz
